### ISSUE TITLE
How to build the training file `SFT_aligned_llama2-7b-chat-hf_train.csv`

### ISSUE THREAD

**Issue by alanxmay** [boyiwei/CoTaEval#1]
Hi, amazing work from your team. I want to replicate the experimental results using other models, I'm curious how the dataset is constructed exactly.

Found `SFT_aligned_llama2-7b-chat-hf_train.csv` in `lib/data.py`

```python
# Load and process aligned dataset
def get_align(nsamples, seed, seqlen, tokenizer, disentangle=False, mode="base"):
    # Load train and test datasets
    if mode == "short":
        data_files = {"train": "./data/SFT_aligned_llama2-7b-chat-hf_train_short.csv"}
    else:
        data_files = {"train": "./data/SFT_aligned_llama2-7b-chat-hf_train.csv"}
    traindata = load_dataset("csv", data_files=data_files, split="train")
    ...
```

Can you publish the code that generate the file `SFT_aligned_llama2-7b-chat-hf_train.csv`?

Thanks!

**Comment by boyiwei** [comment]
Hi. Sorry for the confusion. This file is redundant in this project and I have deleted it. If you have any other questions please let me know. Thanks!

**Comment by alanxmay** [comment]
@boyiwei Thanks for your replay. My question is how can I reproduce the fine-tuning process. Specifically, how the training data is constructed, e.g. what are the inputs, what are the targets.

Maybe a few of examples can explain it. Thanks!

It would be nice if you can publish the training code that produce model `swj0419/llama2-7b_chat_newsqa`! Thanks!

**Comment by boyiwei** [comment]
Hi, we use the modified NewsQA dataset for fine-tuning, which is available here: https://huggingface.co/datasets/boyiwei/newsqa. 

We do the next-token prediction task during the fine-tuning, but we are using the internal scripts from Meta so unfortunately we cannot make it public. Sorry about that!

**Comment by alanxmay** [comment]
@boyiwei Appreciate your replay, thanks for letting me know.
