### ISSUE TITLE
Question about width and choice of n of bloom filters

### ISSUE THREAD

**Issue by guangyaodou** [boyiwei/CoTaEval#3]
Hi,

Suppose the intervention method is "mem_free_tokenized_consecutive". In this case, suppose we set n=6, we will we create a bloom filter with the name "booksum_tokenized.36-36.bf" by running create_bf.py, with a width of 36. 

Later when we run main.py, the [n](https://github.com/boyiwei/CoTaEval/blob/main/main.py#L93) would be 36, and we further set the [width](https://github.com/boyiwei/CoTaEval/blob/main/main.py#L99) to be 66? Is this correct?

I am asking because the output is blank if I run MT-bench using Llama3.1-8B model with the mem_free intervention, and I am trying to debug. 

Thank you!

**Comment by boyiwei** [comment]
Hi, sorry for the confusion. The n=6 means we store 6-grams inside the bloom filter. However, when using memfree in a tokenized way, we store each token with a 6-digit number in a string format. Therefore, each 6-gram stored in the bloom filter will look like a string with len(string)=36. For the [width](https://github.com/boyiwei/CoTaEval/blob/main/main.py#L99) you mentioned here, is the window size for overlap detection, i.e., we inspect output[len(output)-width:] to find if there are any matches inside the bloom filter. Here we set the width=2n-1, if in a tokenized way, it is equivalent to width=2*len(string) -6=66. It is correct.
Feel free to let me know if you encounter further questions.
